### ISSUE TITLE
Broken links on FAQ

### ISSUE THREAD

**Issue by Baa14453** [space-wizards/website-content#39]
The following links on the [FAQ](https://spacestation14.io/about/faq/) don't go to the correct pages.

[Game Wiki](https://wiki.ss14.io/)
[Official Forums](https://forum.ss14.io/)
[Discord](https://discord.ss14.io/)

Under:
Q: How do I learn to play the game?
The [player wiki](https://wiki.ss14.io/).

Under:
Q: Can I help?
Discord link.

Under:
Q: Help! My game is crashing, where do I get help?
First Discord link.

**Comment by Silvertorch5** [comment]
Hiya! Thanks for reporting this, I have gone ahead and fixed the redirects on these links. Many thanks!
