### ISSUE TITLE
hovering over header links leaves remains

### ISSUE THREAD

**Issue by AJCM-git** [space-wizards/website-content#4]
when you hover the main header links the text decoration leaves some remains
![image](https://user-images.githubusercontent.com/60196617/82332690-b601fa00-99b3-11ea-9e53-10b55bc714dd.png)

**Comment by PJB3005** [comment]
That's almost certainly a browser bug.

**Comment by AJCM-git** [comment]
How much do you hate this as a fix? https://cdn.discordapp.com/attachments/240556998112968704/712422027872436234/simplescreenrecorder-2020-05-19_17.33.01.mp4

**Comment by PJB3005** [comment]
Change the colors a bit so they're not as harsh and it's probably fine.
